; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-wrover-mgn4r8]
platform = espressif32
board = esp-wrover-kit
framework = arduino
board_build.partitions = partitions_ota.csv
monitor_speed = 115200
upload_port = COM18
monitor_port = COM18
build_flags =
  -DBOARD_HAS_PSRAM
lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit SSD1306
  bblanchon/ArduinoJson

[env:display]
platform = espressif32@6.8.1
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
build_src_filter =
  -<*>
  +<../Display/main.cpp>
build_flags =
  -I Display
lib_deps =
  https://github.com/moononournation/Arduino_GFX.git#v1.4.7
  witnessmenow/UniversalTelegramBot
  bblanchon/ArduinoJson
lib_ignore =
  Adafruit GFX Library
  Adafruit SSD1306

[env:display-devkit]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM17
monitor_port = COM17
build_src_filter =
  -<*>
  +<../Display_devkit/main.cpp>
lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit ST7735 and ST7789 Library
